name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  AUTOINSTALL: true
  CHANNEL: nightly
  VERBOSE: true
  CI: true
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-x86_64-unknown-linux-musl-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - run: make ci-sweep
      - env:
          PASS_FEATURES: "default-cmake"
        run: make package-x86_64-unknown-linux-musl-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl.tar.gz"

  build-x86_64-unknown-linux-gnu-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          PASS_FEATURES: "default"
        run: make package-x86_64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm"

  build-aarch64-unknown-linux-musl-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
          PASS_FEATURES: "default-cmake"
        run: make package-aarch64-unknown-linux-musl-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm64.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-arm64.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.aarch64.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.aarch64.rpm"

  build-aarch64-unknown-linux-gnu-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
          PASS_FEATURES: "default"
        run: make package-aarch64-unknown-linux-gnu-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu.tar.gz"

  build-armv7-unknown-linux-gnueabihf-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make ci-sweep
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-gnueabihf-all
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf.tar.gz"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armhf.deb
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armhf.deb"
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-1.armv7.rpm
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.armv7.rpm"

  build-armv7-unknown-linux-musleabihf-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - run: make ci-sweep
      - env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-musleabihf
      - uses: actions/upload-artifact@v1
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf.tar.gz
          path: "./target/artifacts/vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf.tar.gz"

  deb-verify:
    needs:
      - build-x86_64-unknown-linux-gnu-packages
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: ["ubuntu:14.04","ubuntu:16.04","ubuntu:18.04","ubuntu:20.04","debian:8","debian:9","debian:10"]
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          apt-get update && \
          apt-get install -y \
          ca-certificates \
          curl \
          git \
          systemd \
          make
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: target/artifacts
      - name: First install of DEB package.
        run: |
          dpkg -i target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb && vector --version
      - name: Second install of DEB package.
        run: |
          dpkg -i target/artifacts/vector-${{ env.VECTOR_VERSION }}-amd64.deb && vector --version

  release-docker:
    runs-on: ubuntu-18.04
    needs:
      - build-aarch64-unknown-linux-musl-packages
      - build-x86_64-unknown-linux-gnu-packages
      - build-x86_64-unknown-linux-musl-packages
      - build-armv7-unknown-linux-musleabihf-packages
      - build-armv7-unknown-linux-gnueabihf-packages
      - deb-verify
    steps:
      - uses: actions/checkout@v1
      - run: echo VECTOR_VERSION=$(make version) >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf.tar.gz
          path: target/artifacts
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-amd64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm64.deb
          path: target/artifacts
      - uses: actions/download-artifact@v2
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armhf.deb
          path: target/artifacts
      - env:
          PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7"
        run: |
          make release-docker
